# Generated by Django 5.0.2 on 2024-02-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
