# Generated by Django 5.0.2 on 2024-02-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_review_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['posted_on']},
        ),
    ]
